lnu-norge/lokaler.lnu.no

- .rubocop.yml
- app/controllers/spaces_controller.rb
- app/models/space.rb
- app/views/spaces/_image_list.html.erb
- app/views/spaces/_space_listing.html.erb
- app/views/spaces/index.html.erb
- config/routes.rb
- db/migrate/20210922082655_create_active_storage_tables.active_storage.rb
- db/schema.rb
Add support for uploading images to spaces
This adds a new route `POST spaces/upload_image` which will append an image to the space
> Add image upload

- Dockerfile
- config/environments/development.rb
- docker-compose.yml
- entrypoint.sh
Added Dockerfile and docker-compose, made a change in environments/development to allow RFC1918 IPs if dockerized-ENV is set, since containers can have dynamic IPs
> Adding support for docker

- app/javascript/stylesheets/application.scss
- app/javascript/stylesheets/common_elements.scss
- app/views/active_storage/blobs/_blob.html.erb
Simple code that makes attachments added in Trix downloadable by user. 
To dos:
> Made attachments downloadable

- .env.example
- .gitignore
- .rubocop.yml
- Gemfile
- app/controllers/spaces_controller.rb
- app/javascript/controllers/mapbox_controller.js
- app/views/layouts/application.html.erb
- app/views/spaces/index.html.erb
- config/routes.rb
- config/webpack/environment.js
- package.json
- yarn.lock
**To test**
Copy `.env.example` to `.env`
Set `MAPBOX_API_KEY` to a valid mapbox api key
> Added a mapbox stimulus controller

- app/javascript/custom/custom_trix.js
- app/javascript/packs/application.js
- app/javascript/stylesheets/space.scss
Custom loading trix with some configurations to allow `<p>` tags and to make it easy to add other configurations later.
> Got trix to work with <p> tags

- .eslintrc.js
- .overcommit.yml
- Gemfile
- app/controllers/spaces_controller.rb
- app/javascript/controllers/application.js
- app/javascript/controllers/example_controller.js
- app/javascript/controllers/index.js
- app/javascript/controllers/mapbox_controller.js
- app/views/layouts/application.html.erb
- app/views/spaces/_space_dev_information.html.erb
- app/views/spaces/_space_listings.html.erb
- app/views/spaces/index.html.erb
- package-lock.json
- package.json
- spec/fabricators/space_fabricator.rb
- yarn.lock
Changed the response of spaces_in_rect to 
```
{ 
listing: "html for displaying space listings",
markers: [array of map markers] 
}
```
And the javascript controller will then take the html generated by the server and place it under the map, I was originally planning to use TurboStream for this, but seems like this way is easier and should work just as well
> Update space listing when map moves around

- Gemfile
- Gemfile.lock
- Guardfile
Test it out! (Needs bundle install)
Script just copied from the standard rspec-guard gem. 
I think it seems pretty sweet, so far!
> Add rspec autorun to Guardfile

- README.md
- db/seeds.rb
- db/seeds/reviews/reviews.rb
Works by setting `heroku config:set SEED_FILE=development` for development.rb, or you can set it to any other file in the seeds folder. Overrides loading from the current enviroment. 
Then simply run `heroku run rails db:seed`
To unset, use `heroku config:unset SEED_FILE` 
Todos:
> Make it possible to seed Heroku with non-production files

- Gemfile
- Gemfile.lock
- app/controllers/users/devise_controller.rb
- app/controllers/users/registrations_controller.rb
- app/javascript/controllers/index.js
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_back.html.erb
- app/views/devise/shared/_user_form.html.erb
- app/views/layouts/application.html.erb
- config/initializers/simple_form.rb
- config/initializers/simple_form_tailwind.rb
- config/locales/simple_form.en.yml
- config/locales/simple_form.nb.yml
- config/routes.rb
- lib/templates/erb/scaffold/_form.html.erb
Added simple form for devise
Skipped other models so we can devide and conquer. 
Added edit account button to temp menu
> Simple forms

- app/javascript/controllers/flash_controller.js
- app/views/shared/_flash.html.erb
Fix so that flashmessages actually gets removed, not only hidden.
> Add stimulus target to remove flashmessages from dom

- app/views/reviews/_review_content.html.erb
- app/views/reviews/form/_type_of_contact.html.erb
- app/views/reviews/new/_facility_buttons.html.erb
- app/views/shared/_modal.html.erb
- app/views/space_contacts/_space_contact.html.erb
- app/views/spaces/edit/common/_editable_inline.html.erb
- app/views/spaces/index.html.erb
- app/views/spaces/index/_search_form.html.erb
- app/views/spaces/show/_facility_item.html.erb
- app/views/spaces/show/_image_header.html.erb
Siden vi bruker sprockets så bør vi også bruke `inline_svg_tag`
> Fix all uses of inline_svg to use the sprockets version _tag

- app/controllers/spaces_controller.rb
- app/views/spaces/index/_search_form.html.erb
This is just a cleanup of some n+1 queries, reduces the amount of queries from moving the map substantially.
> Remove n1 queries

- app/javascript/controllers/slider_controller.js
- app/javascript/stylesheets/application.scss
- app/javascript/stylesheets/space_index.scss
- app/views/shared/_image_slider.html.erb
- app/views/spaces/index/_image_preview.html.erb
- app/views/spaces/index/_space_listing.html.erb
Also lazy loads images in slider, and adds primitive fall back for non-js users.
> Space index slider

- app/controllers/spaces_controller.rb
Hvis 2 lokaler har lik fasilitets score så vil de blir sortert etter star rating
> Sort by star rating

- app/javascript/controllers/mapbox_controller.js
- app/views/spaces/index/_filter_button.html.erb
Viser alle søkefilterene under søkebaren.
> Display selected filters under the searchbox

- app/javascript/controllers/application.js
- app/javascript/controllers/mapbox_controller.js
URLen vil bli se sånn her ut
`http://localhost:3000/spaces?selectedLocation=59.9085%2C9.7548%2C8.81033110943973&selectedFacilities=Overnatting%2CDusjer%2CAuditorium%2CGymsal%2CSpisesal%2CProsjektor`
> Add search options to url

- .github/workflows/ruby.yml
- .rubocop.yml
- app/controllers/spaces_controller.rb
- app/models/space.rb
- spec/requests/review_spec.rb
This PR makes github actions run rubocop, I have noticed that we have had a few rubocop issues for some time now.
This pr also removes previous rubocop errors that were present
- Increased the AbcSize to 20 as we hit the limit way to fast
> Add a rubocop runner to github actions

- app/views/spaces/create/_form.html.erb
- app/views/spaces/new.html.erb
Styes header and buttons. 
Too narrow right now due to depending on #116 to not have to deal with the flex situation, so that will be fixed in #116
> Add simple styling for new space form

- app/javascript/controllers/index.js
- app/javascript/controllers/trix_paste_controller.js
- app/views/spaces/edit/common/_edit_rich_text.html.erb
- config/initializers/simple_form_tailwind.rb
When pasting a URL we will convert it to a clickable link
Taken from https://dev.to/sowenjub/auto-linking-urls-with-trix-editor-and-stimulusjs-4gh8
> Pasting in text will convert to url

- db/seeds/imports/nsr/helpers.rb
- db/seeds/imports/nsr/import_function.rb
There were some broken schools without addresses that screwed up import. Fixed here by simply excluding them.
> Fix NSR import on main

- db/seeds/imports/nsr/helpers.rb
- db/seeds/imports/nsr/import_function.rb
Fixes errors with space_contacts that don't belong to a space all being placed on the first space.
> Fix nsr import, part deux

- app/controllers/application_controller.rb
- app/controllers/reviews_controller.rb
- app/models/organization.rb
- app/models/review.rb
- app/models/user.rb
- app/views/devise/shared/_user_form.html.erb
- app/views/reviews/_review_content.html.erb
- app/views/reviews/form/_text_been_there.html.erb
- config/locales/nb.yml
- config/locales/simple_form.nb.yml
- db/migrate/20220117122937_remove_organization.rb
- db/migrate/20220117123518_add_organization_to_user_review.rb
- db/schema.rb
- spec/fabricators/review_fabricator.rb
- spec/features/user_views_homepage_spec.rb
[Trello](https://trello.com/c/rD1EofXO/205-ha-organisasjon-som-fritekstfelt-p%C3%A5-review-i-stedet-for-model-i-alle-fall-enn-s%C3%A5-lenge)
> Change organization to a free text field

- app/controllers/spaces_controller.rb
- app/models/review.rb
- spec/features/user_manages_space_spec.rb
[Trello](https://trello.com/c/ewVi1Ucg/239-kan-ikke-endre-til-ingen-andre-lokaler-p%C3%A5-spacegroup)
> Fix when user fills in empty space groups when editing spaces

- app/views/reviews/_form.html.erb
- app/views/reviews/form/_more_about_your_stay.html.erb
- app/views/reviews/form/_text_been_there.html.erb
- app/views/reviews/new/_star_rating.html.erb
- app/views/reviews/new_been_there.html.erb
- app/views/reviews/new_not_allowed_to_use.html.erb
- app/views/reviews/new_only_contacted.html.erb
Adds simple form wrappers (and therefore error handling) to Review#new
Does not add it for facilities, as those will probably change in the near future.
> Add simple form to review

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
This should save the last location you tried to access as not logged in
If no such location exists it will use default root path
To test:
While not logged in:
Go to localhost:3000/spaces/3
You should now be redirected to login screen
Log in
You should now be redirect to localhost:3000/spaces/3
> Remember path before login

- app/views/spaces/show/_reviews.html.erb
> Only show one Add Review button when no reviews are available

- app/assets/stylesheets/admin/dashboard.scss
- app/controllers/admin/dashboard_controller.rb
- app/helpers/admin/dashboard_helper.rb
- app/views/admin/dashboard/index.html.erb
- config/locales/nb.yml
- config/routes.rb
Added a admin/dashboard-controller with index for /admin
> Add admindashboard index

- app/controllers/facility_reviews_controller.rb
- app/models/space.rb
- app/views/facility_reviews/new/_facility_buttons.html.erb
- app/views/facility_reviews/new/_facility_category.html.erb
Fix an issue that caused the facility review edit to be empty. Or show incorrect reviews
> Fix a few issues causing incorrect facility reviews when editing

- app/controllers/facility_reviews_controller.rb
- app/models/space.rb
- app/views/facility_reviews/new.html.erb
While reviewing I did some experiments to see if I understood the problems correctly. I think they may have solved the problems, but letting that be up to @mathias234.
See review of #184 for more info.
> Review branch for space=type to facility link

- app/javascript/controllers/mapbox_controller.js
Fetches all facilities in area after searching for a location
> Update location once a flyTo/fitBounds happens

- app/models/space.rb
@mathias234 FYI. Small error in my branch. should probably be merged before merging to prod.
> Fix scoring, star rating should only matter to space score once

- app/controllers/facility_reviews_controller.rb
- app/javascript/controllers/sync_fields_with_same_id.js
- app/models/space.rb
- app/models/space_facility.rb
- app/views/facility_reviews/new.html.erb
- app/views/facility_reviews/new/_facility_buttons.html.erb
- app/views/facility_reviews/new/_facility_category.html.erb
- app/views/spaces/edit/common/_editable_inline.html.erb
- app/views/spaces/show/_facilities.html.erb
- config/locales/nb.yml
- db/migrate/20240216091620_add_unique_constraint_to_space_facility_index.rb
- db/schema.rb
- spec/fabricators/facilities_category_fabricator.rb
- spec/fabricators/facility_fabricator.rb
- spec/fabricators/image_fabricator.rb
- spec/fabricators/space_fabricator.rb
- spec/fabricators/space_facility_fabricator.rb
- spec/fabricators/space_types_facility_fabricator.rb
- spec/features/user_creates_facility_reviews_spec.rb
- spec/features/user_views_homepage_spec.rb
- spec/support/user_creates_facility_reviews_helpers.rb
This PR refactors a lot of the code around facility reviews, and adds feature tests running on capybara to make sure everything works. 
There are still untested paths, but I think this gives us a lot more confidence, and I hope the code is easier to read and reason about than the old code was.
> Fix bug where facility reviews were broken

- app/controllers/spaces_controller.rb
- app/javascript/controllers/duplicate_checker_controller.js
- app/javascript/controllers/mapbox_controller.js
- app/javascript/controllers/search_and_filter/capsule_html.js
- app/models/space.rb
- app/services/spaces/duplicate_detector_service.rb
- app/views/spaces/index/_filter_button.html.erb
- app/views/spaces/index/_filters.html.erb
- app/views/spaces/index/_search_form.html.erb
- config/locales/nb.yml
This adds two new features: 
- The ability to search by the title of a space on the index
- The ability to search by the title of a space on the duplicate finder in space#new 
It does so in a very naïve way, and should probably be redone to be more performant and fault tolerant by switching to a proper search engine, but that's out of scope of the current work.
> Search by space title

- app/javascript/controllers/mapbox_controller.js
With this, we no longer fly to location - but just jump there, instantly. I've also fixed the "Gjøvik" bug found in user testing.
> Instant search by location

- app/models/space.rb
- db/seeds/imports/nsr/helpers.rb
- db/seeds/imports/nsr/import_function.rb
This just updates the seed for NSR data, not with new data, but so we can test with loads of spaces again.
> Fix old NSR imports

- app/controllers/facility_reviews_controller.rb
- app/models/facility_review.rb
- app/models/space.rb
- app/models/space_types_facility.rb
- app/models/space_types_relation.rb
- app/services/spaces/aggregate_facility_reviews_service.rb
- app/services/spaces/concerns/countable_reviews.rb
- db/migrate/20240302202011_add_indexes_for_aggregations.rb
- db/schema.rb
- spec/fabricators/facility_review_fabricator.rb
- spec/fabricators/space_types_facility_fabricator.rb
- spec/services/spaces/aggregate_facility_reviews_service_spec.rb
I tried some experiments to see if I could get it faster, but only got marginal gains. Still worth keeping. Somewhat clearer code too.
> Minor performance improvements for aggregations

- app/assets/stylesheets/space_index.css
- app/controllers/spaces/map_vector_controller.rb
- app/javascript/controllers/nested_checkbox_filter_controller.js
- app/views/layouts/application.html.erb
- app/views/personal_space_lists/_card_for_spaces_index.html.erb
- app/views/personal_space_lists/card/_title.html.erb
- app/views/personal_space_lists/space_in_list/_list_status_for_space.html.erb
- app/views/spaces/index.html.erb
- app/views/spaces/index/_facility_item.html.erb
- app/views/spaces/index/_filter_button.html.erb
- app/views/spaces/index/_filter_capsules.html.erb
- app/views/spaces/index/_filters.html.erb
- app/views/spaces/index/_image_preview.html.erb
- app/views/spaces/index/_map.html.erb
- app/views/spaces/index/_map_marker.html.erb
- app/views/spaces/index/_map_marker_list_status.html.erb
- app/views/spaces/index/_search_form_fields.html.erb
- app/views/spaces/index/_space_facility_listing.html.erb
- app/views/spaces/index/_space_listing.html.erb
- app/views/spaces/index/_space_listing_header.html.erb
- app/views/spaces/index/_space_listings.html.erb
- app/views/spaces/index/search_form_fields/_filter_on_facilities.html.erb
- app/views/spaces/index/search_form_fields/_filter_on_location.html.erb
- app/views/spaces/index/search_form_fields/_filter_on_space_types.html.erb
- app/views/spaces/index/search_form_fields/_filter_on_title.html.erb
- config/locales/space_filter.nb.yml
> Nicer search UI

- app/views/devise/sessions/edit.html.erb
- app/views/layouts/menu/_account_menu_item.html.erb
- app/views/layouts/menu/_menu.html.erb
> Show who is logged in in the menu and on the session page.
