- app/models/aggregated_facility_review.rb
- app/models/facility_review.rb
- app/models/space.rb
- app/services/application_service.rb
- app/services/spaces/aggregate_facility_reviews.rb
- db/migrate/20210921092427_create_facility_reviews.rb
- db/migrate/20210921103923_create_aggregated_facility_reviews.rb
- db/schema.rb
- spec/fabricators/facility_review_fabricator.rb
- spec/models/facility_review_spec.rb
- spec/services/spaces/aggregate_facility_reviews_spec.rb
Add the FacilityReview model
This model holds a review for a specific facility in a space.
This PR also contains a first stab at implementing a system for aggregating facility reviews.
> Add facility reviews

- app/javascript/stylesheets/common_elements.scss
- app/javascript/stylesheets/space.scss
- app/views/spaces/_space_listing.html.erb
As well as global styling for `<a>`, and an '.unstyled-link' class that can be added to an `<a>` to negate the global styling.
> Added basic styling for p, h1, ul, and a for spaces 

- app/models/aggregated_facility_review.rb
- app/models/facility_category.rb
- app/models/space.rb
- app/views/spaces/show/_facilities.html.erb
- db/seeds/defaults/a11y_facilities.rb
This PR adds facilities like this to each Space#show:
To get it to work properly, you might have to re-run seeds with db:reset, or you will get the wrong titles for each category. 
It introduces some new code that I'm uncertain about, and would love a review on!
In particular, looking for reviews on the `tooltip` method I added to AggregatedFacilityReview. Is that the right place for it?
Also looking for a review on how to efficiently join AggregatedFacilityReview data with Facility data for a given Space. Currently I do it through Ruby, and I'm almost certain there must be a better way to do it through SQL / ActiveRecord: 
We also get some technical debt in the partial `_facilities.html.erb` and afforamentioned methods by not modelling the future "Facilities we have selected" feature …
> Show facilities, and tooltip for them

- app/models/space.rb
- config/initializers/action_text_paper_trail.rb
- db/migrate/20211011115122_add_object_changes_to_versions.rb
- db/schema.rb
Experimented a little with paper trail to see if it fit our demands, and found it lacking for actiontext, diffs, and star ratings. 
This PR adds paper trail to actiontext, skip star rating for paper trail (as it's generated by reviews, not versioned), and add diffs to paper trail.
To use for actionText:
```ruby
@space..who_can_book.versions # Paper trail for who_can_book. Same syntax for other rich text fields.
@space.versions # Paper trail for title, fits_people, address and all the other basic information
```
To see diff for a given version:
``` ruby
@space.versions.last.changeset 
```
> Changes to paper trail config, to make it ready for versions in the future

- Gemfile
- Gemfile.lock
- app/controllers/spaces_controller.rb
- app/helpers/spaces_helper.rb
- app/javascript/controllers/autofilladdress_controller.js
- app/models/space.rb
- app/services/spaces/location_search_service.rb
- app/views/spaces/create/_form.html.erb
- app/views/spaces/edit/_address.html.erb
- app/views/spaces/edit/_basics.html.erb
- app/views/spaces/edit/_where.html.erb
- app/views/spaces/show/_where.html.erb
- config/definitions.rb
- config/locales/nb.yml
- config/routes.rb
- spec/rails_helper.rb
- spec/services/spaces/location_search_service_spec.rb
- spec/support/vcr/location_search_address.yml
- spec/support/vcr/location_search_address_postcode.yml
- spec/support/vcr/location_search_postaddress.yml
- spec/support/vcr/location_search_postcode.yml
- spec/views/spaces/show.html.erb_spec.rb
No design work has been done here, it still uses the  green create space CRUD on the main page
It works by the frontend sending a query to the backend which uses Geonorge API to figure out the lat lng of the typed address. if there is no javascript enabled on the frontend the fields will not automatically fill out but the backend will still try to figure out the coordinates based on what was submitted in the form.
> Autofill address when creating space

- app/controllers/spaces_controller.rb
https://trello.com/c/m3NlBbrm/131-spaceupdate-d%C3%B8r-pga-hash-feil
Buggen ga feilmelding: 
```
TypeError (no implicit conversion of nil into Hash):
app/controllers/spaces_controller.rb:51:in `update'
```
Som gjaldt denne kodesnutten: 
```ruby
if @space.update(
**space_params,
**address_params
)
```
Ved å sørge for at address_params alltid er en hash så løste det seg.
> Fix bug where Space#update was blocked when address wasn't changed

- app.json
- config/environments/production.rb
This is required for sendgrid to work, will not work on the review apps as they don't have the ENV["HOST"] set
> Add default url option to production as env variable

- Gemfile
- Gemfile.lock
- app/helpers/parse_url_helper.rb
- db/seeds/imports/nsr/helpers.rb
- db/seeds/imports/nsr/import_function.rb
- db/seeds/imports/nsr/readme.md
- db/seeds/nsr.rb
Imports schools from NSR, and adds them. Tries not to duplicate things.
To run the import, set the flag SEED_FILE to nsr before running seed (or reset):
```bash
SEED_FILE=nsr rails db:seed
```
(Can be it's own PR and card)
> Import data from NSR through seed

- app/controllers/spaces_controller.rb
- app/javascript/controllers/mapbox_controller.js
- app/views/shared/_flash.html.erb
- app/views/spaces/index/_space_facility_listing.html.erb
- app/views/spaces/index/_space_listing.html.erb
- app/views/spaces/index/_space_listings.html.erb
Makes sure the list of spaces show which of the filtered facilities it matches.
Also fixes some bugs in the filter, where no filters other than Overnatting could be set.
Exposes a new bug in the NSR imports, which is that we haven't run aggregated search and therefore have nil values for all experiences. Added a comment to that one in the relevant PR.
> Facilities listing in search

- app/javascript/stylesheets/application.scss
- app/javascript/stylesheets/map.scss
When hovering a map marker, it now is on top and is possible to read:
> Make sure hovered map marker is on top of the other markers

- app/controllers/spaces_controller.rb
- app/views/spaces/index.html.erb
- app/views/spaces/index/_space_listing_header.html.erb
- app/views/spaces/index/_space_listings.html.erb
- config/locales/nb.yml
- spec/views/spaces/index.html.erb_spec.rb
Depends on #93 and builds on that PR. Should not be merged until #93 is merged.  Temporarily set up to merge against #93 so it's easier to see what's new, and should not be merged until it's changed back to merge to main!
Adds counts to search, as in Figma sketch, and sets a page size default that is shared with the view.
Also adds a little placeholder footer if the search count is higher than the page size, that is - if content is hidden from view: 
In the future, we probably want pagination instead of this.
> Add search count to search index

- Gemfile.lock
This was added by bundle install. Not sure if it should replace the line above or not.
> Add mac 21, as required by ruby 3.0.3

- app/models/facility_review.rb
- app/models/review.rb
- spec/models/review_spec.rb
- spec/models/space_spec.rb
- spec/services/spaces/aggregate_facility_reviews_service_spec.rb
This changes when the aggregator is ran and results in a decrease from 2sec to 300ms to create a new review.
The old way would cause the aggregator to rerun for every facility review so it would run 13 times on when creating a review with our current facility setup.
> Move aggregating of reviews to the Review model

- app/views/spaces/show/_basics.html.erb
Previously we would show the url like this, if it was saved as an empty string:
Now it hides it if the string is not `.present?`
> Also hide the URL if it's just an empty string

- app/javascript/stylesheets/tom_select.scss
From:
To:
Before it was invisible on focus, but now it shows and rotates from:
to
> Dropdown styling: Minor fixes

- app/models/review.rb
- db/migrate/20220118072558_change_reveiew_price_column_to_string.rb
- db/schema.rb
- spec/models/review_spec.rb
This solves a user issue we found in user testing, where the user set the price of a review to "30 000" and was rebuked. It does so by doing two things: Storing the price as a string (we won't do calculations on it anyway), and replacing " " with "" on that string before validating that it's still a number.
We might want to remove the validation that it's a number entirely, so someone can write "Price: We had to volunteer in the gardens" but I'm not sure if that's useful or just allows for too much weird formatting on the numbers.
> Allow review.price to be input with a space by user

- app/javascript/controllers/mapbox_controller.js
- app/views/spaces/index/_search_form.html.erb
[Denne PR løser to ting: ](https://trello.com/c/pAhCEUx8/224-s%C3%B8keboks-sette-focus-n%C3%A5r-du-%C3%A5pner-den-og-lukke-boksen-p%C3%A5-enter)
1. Når du klikker søke filter knappen vil den autofokuse på tekstfeltet
2. Når du trykker enter uansett sted inne i modalen vil modalen lukkes
Issues oppdaget: Søket kjøres ikke når modalen lukkes (både på enter og med klikk), det betyr at man for eksempel blir vist Fredrikstad, men må klikke på kartet for å få opp søkeresultatene for det området.
> Søkeboks sette focus når du åpner den og lukke boksen på enter

- app/helpers/modal_helper.rb
- app/models/space.rb
- app/views/spaces/show/_facilities.html.erb
- app/views/spaces/show/_facility_item.html.erb
This branch:
It does not:
Desktop:
Mobile:
> Clean up visually on Space#show facilities

- app/helpers/modal_helper.rb
- app/javascript/controllers/mapbox_controller.js
- app/models/space.rb
- app/views/spaces/index/_filter_button.html.erb
- app/views/spaces/index/_map.html.erb
- app/views/spaces/show/_facilities.html.erb
- app/views/spaces/show/_facility_item.html.erb
Takes a fresh look at the search buttons, and cleans up a litte.
Moves the  GPS button out to the map, in a new corner designated for "map manipulation buttons", such as a plus and minus (which I think we need to add after it was voiced in a user interview with someone who didn't have a great mouse at her disposal)
Moves the chosen facility buttons under the search bar: 
And cleans up the search bar so it's a complete button again:
> Search button revamp

- app/views/layouts/application.html.erb
- app/views/layouts/menu/_menu.html.erb
- app/views/pages/privacy_policy.html.erb
- config/locales/menu.nb.yml
Adds a simple privacy policy page, as required by law and Google.
Also adds a simple footer to keep the privacy policy in:
And shows the menu (sans menu items) when not logged in, to give context on the not-logged in privacy policy page.
> Privacy policy

- app/controllers/facility_reviews_controller.rb
- app/controllers/spaces_controller.rb
- app/helpers/modal_helper.rb
- app/javascript/controllers/equal_checkboxes_handler_controller.js
- app/javascript/controllers/hide_controller.js
- app/javascript/controllers/index.js
- app/javascript/controllers/sync_fields_with_same_id.js
- app/javascript/stylesheets/common_elements.scss
- app/javascript/stylesheets/editable.scss
- app/javascript/stylesheets/forms.scss
- app/javascript/stylesheets/radio_slider.scss
- app/models/space.rb
- app/services/spaces/aggregate_facility_reviews_service.rb
- app/views/admin/space_types/_form.html.erb
- app/views/facility_reviews/new.html.erb
- app/views/facility_reviews/new/_facility_buttons.html.erb
- app/views/facility_reviews/new/_facility_category.html.erb
- app/views/spaces/edit/_facility_description.html.erb
- app/views/spaces/show/_facilities.html.erb
- app/views/spaces/show/_facility_item.html.erb
- config/locales/nb.yml
- config/locales/simple_form.nb.yml
- config/routes.rb
Too large a PR, sorry about that.
This attempts to make facilities editable in a semi-sane way:
And added a description for why some facilities are hidden.
> Edit facilities

- app/views/layouts/menu/_menu.html.erb
> Fix overlap between footer and menu on mobile

- app/controllers/facility_reviews_controller.rb
- app/models/space.rb
- app/models/space_facility.rb
- app/models/space_types_facility.rb
- app/models/space_types_relation.rb
- app/services/spaces/aggregate_facility_reviews_service.rb
- app/views/spaces/index/_search_form.html.erb
- app/views/spaces/index/_space_facility_listing.html.erb
- db/migrate/20220217073115_add_relevant_integer_to_space_facility.rb
- db/schema.rb
- spec/services/spaces/aggregate_facility_reviews_service_spec.rb
Two changes should be done to improve the feel of the app, but can be done in future PRs:
> Fix n 1 problem in search

- app/controllers/facility_reviews_controller.rb
- app/models/space_types_relation.rb
- app/services/spaces/aggregate_facility_reviews_service.rb
(Made this just to see if I could! Not billable hours for me)
This should cut aggregation time to 1/3 for aggregating facilities for all spaces, and make it near instant when adding facility reviews for a space.
Should be tested a bit as it touches core functions, and unfortunately it seems like our test coverage of facility reviews is fairly low.
This branch: 
And uses the ability in AggregateFacilityReviewsService to add a list of facilities to run to only aggregate relevant facilities for the following cases: 
All in all this means that the UX is now much smoother when doing things that trigger aggregation.
Not tackled in this branch
> Quicker aggregation

- config/environments/production.rb
Testing if we still need this. Was only needed in prod, so testing there now.
> No longer set the harmful assets compile true setting

- config/locales/nb.yml
- spec/fabricators/user_fabricator.rb
- spec/features/user_resets_password_spec.rb
- spec/features/user_signs_in_spec.rb
- spec/features/user_signs_out_spec.rb
- spec/features/user_signs_up_spec.rb
- spec/support/devise.rb
- spec/support/devise_helpers.rb
Generated tests with the devise-specs gem, then adapted them to our code base. It's only feature tests, so they are a bit slow, but should stop us having basic bugs where stuff just breaks, like the email link did.
> Add tests for devise

- Gemfile
- Gemfile.lock
- app/models/space.rb
- app/services/spaces/aggregate_facility_reviews_service.rb
- app/services/spaces/concerns/countable_reviews.rb
- spec/features/user_creates_facility_reviews_spec.rb
- spec/services/spaces/aggregate_facility_reviews_service_spec.rb
- spec/spec_helper.rb
- spec/support/performance_benchmark.rb
- spec/support/user_creates_facility_reviews_helpers.rb
> Fix aggregation destroying unrelated stuff + terrible performance

- app/assets/stylesheets/application.css
- app/assets/stylesheets/show-only-if-inside-space-open-in-sidebar.css
- app/javascript/controllers/mapbox_controller.js
- app/models/image.rb
- app/views/space_images/_image_slider.html.erb
- app/views/spaces/_back_to_search_button.html.erb
- app/views/spaces/index.html.erb
- app/views/spaces/index/_map.html.erb
- app/views/spaces/index/_space_listing.html.erb
- app/views/spaces/show.html.erb
- app/views/spaces/show/_image_header.html.erb
- tailwind.config.js
As suggested in user testing, when opening a Space while filtering, this will opens it over the map on the right (or beside it), if there is room for that. 
Using this UX, I feel much more comfortable going through multiple spaces and comparing them, without losing my search.
I now think we have done everything we will do to improve the default search before moving on to ringelister. 
One thing that would improve it further: Somehow saving the filter states, so we can keep them cross-navigation. At the moment, you can end up nuking your filters if you navigate back and forth outside the search path. That's not good.
> Open spaces over map

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/forms.css
- app/controllers/admin/dashboard_controller.rb
- app/controllers/admin/menu_controller.rb
- app/controllers/base_controllers/authenticate_as_admin_controller.rb
- app/javascript/application.js
- app/models/user.rb
- app/views/admin/dashboard/_statistics_box.html.erb
- app/views/admin/dashboard/_tiny_pie_chart.html.erb
- app/views/admin/dashboard/_user_with_change_count.html.erb
- app/views/admin/dashboard/index.html.erb
- app/views/admin/menu/_admin_boxed_menu.html.erb
- app/views/admin/menu/_admin_menu.html.erb
- app/views/admin/menu/_admin_menu_item.html.erb
- app/views/admin/menu/_admin_menu_items.html.erb
- app/views/admin/menu/index.html.erb
- app/views/devise/sessions/edit.html.erb
- app/views/layouts/admin/authenticated_as_admin.html.erb
- app/views/layouts/application.html.erb
- config/initializers/chartkick.rb
- config/locales/admin.nb.yml
- config/locales/date_periods.nb.yml
- config/routes.rb
- package.json
- tailwind.config.js
- yarn.lock
Adds a simple admin menu in the profile page for admins:
And a statistics page with filterable numbers from the database: 
Currently does not integrate with Posthogs tracking of visitors, but we might want to track visitors and use that for conversion rates.
> Statistics for administrators
